---
abstract: '3D mutation proximity & cluster analysis'
author:
  - 'Beifang Niu, Adam D Scott, & Sohini Sengupta from McDonnell Institute of Washington University at St. Louis'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HotSpot3D
version: 0.2
